name: Linux

on:
  release:
    types: [released,prereleased]

jobs:
  jar:
    name: 🐧 .jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 23
      - name: Build jar
        run: mvn clean install -Dmaven.javadoc.skip=true -B -V
      - name: Create deploy directory
        run: mkdir deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Copy jar to deploy dir
        run: cp -v "savegame-editor/target/$(ls savegame-editor/target | grep jar-with-dependencies)" deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Compress release
        run: zip -r "GTA:SA-Savegame-Editor.jar.zip" "deploy"
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./GTA:SA-Savegame-Editor.jar.zip
          asset_name: GTA:SA-Savegame-Editor.jar.zip
          asset_content_type: application/zip
  deb:
    name: 🐧 .deb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 23
      - name: Build deb
        run: mvn clean install -Pdeb -Dmaven.javadoc.skip=true -B -V
      - name: Create deploy directory
        run: mkdir deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Copy deb to deploy dir
        run: cp -v "savegame-editor/target/$(ls savegame-editor/target | grep .deb)" deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Compress release
        run: zip -r "GTA:SA-Savegame-Editor.deb.zip" "deploy"
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./GTA:SA-Savegame-Editor.deb.zip
          asset_name: GTA:SA-Savegame-Editor.deb.zip
          asset_content_type: application/zip
  rpm:
    name: 🐧 .rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 23
      - name: Build rpm
        run: mvn clean install -Prpm -Dmaven.javadoc.skip=true -B -V
      - name: Create deploy directory
        run: mkdir deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Copy rpm to deploy dir
        run: cp -v "savegame-editor/target/rpm/savegame-editor/RPMS/noarch/$(ls savegame-editor/target/rpm/savegame-editor/RPMS/noarch | grep .rpm)" deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Compress release
        run: zip -r "GTA:SA-Savegame-Editor.rpm.zip" "deploy"
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./GTA:SA-Savegame-Editor.rpm.zip
          asset_name: GTA:SA-Savegame-Editor.rpm.zip
          asset_content_type: application/zip
