name: Windows

on:
  release:
    types: [released,prereleased]

jobs:
  exe:
    name: 🏢 .exe
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Build exe
        run: mvn clean install -Pdeb "-Dmaven.javadoc.skip=true" -B -V -Pwindows
      - name: Create deploy directory
        run: mkdir deploy
        if: startsWith(github.ref, 'refs/tags/v')
      #- name: Create jre directory
      #  run: mkdir deploy\jre
      #  if: startsWith(github.ref, 'refs/tags/v')
      #- name: Copy jre to deploy dir
      #  run: xcopy "%JAVA_HOME%\*" deploy\jre /E/H
      #  if: startsWith(github.ref, 'refs/tags/v')
      - name: Copy app to deploy dir
        run: copy "savegame-editor/target/*.exe" deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Compress release
        run: Compress-Archive "deploy" "GTA-SA-Savegame-Editor.Windows.zip"
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./GTA-SA-Savegame-Editor.Windows.zip
          asset_name: GTA-SA-Savegame-Editor.Windows.zip
          asset_content_type: application/zip
